"""Report generation: JSON (SARIF-inspired), Markdown."""
from __future__ import annotations

import json
import pathlib
import time
from typing import Any

from ..core.result import AttackResult, Severity
from ..core.session import Session


def _sarif_level(sev: Severity) -> str:
    return {"info": "note", "low": "note", "medium": "warning",
            "high": "error", "critical": "error"}[sev.value]


def to_json(session: Session, results: list[AttackResult], output: pathlib.Path) -> None:
    """Write a structured JSON report."""
    doc: dict[str, Any] = {
        "tool": "promptix",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "summary": session.summary(),
        "findings": [r.to_dict() for r in results if r.success],
        "all_probes": [r.to_dict() for r in results],
    }
    output.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")


def to_markdown(session: Session, results: list[AttackResult], output: pathlib.Path) -> None:
    """Write a Markdown pentest report."""
    hits = [r for r in results if r.success]
    summary = session.summary()
    lines: list[str] = [
        "# Promptix — Pentest Report",
        f"**Generated:** {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}  ",
        f"**Target:** `{summary['target']}`  ",
        f"**Probes sent:** {summary['probes']}  ",
        f"**Hits:** {summary['hits']}  ",
        f"**Hit rate:** {summary['hit_rate']:.1%}  ",
        f"**Worst severity:** `{summary['worst_severity'].upper()}`  ",
        "",
        "---",
        "",
        "## Summary by Severity",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in reversed(list(Severity)):
        cnt = summary["by_severity"].get(sev.value, 0)
        if cnt:
            lines.append(f"| {sev.value.upper()} | {cnt} |")
    lines += ["", "---", "", "## Findings", ""]
    if not hits:
        lines.append("_No successful attacks detected._")
    else:
        for r in hits:
            lines += [
                f"### [{r.severity.value.upper()}] {r.module} / {r.technique}",
                f"**Probe ID:** `{r.id}`  ",
                f"**Confidence:** {r.confidence:.0%}  ",
                f"**Latency:** {r.latency_ms:.0f} ms  ",
                "",
                "**Payload:**",
                "```",
                r.payload,
                "```",
                "",
                "**Response (excerpt):**",
                "```",
                r.response[:500] + ("..." if len(r.response) > 500 else ""),
                "```",
                "",
                f"**Indicators:** {', '.join(r.indicators)}  ",
                "",
                "---",
                "",
            ]
    lines += [
        "## Methodology",
        "",
        "Probes are based on the [OWASP Top 10 for LLM Applications](https://owasp.org/www-project-top-10-for-large-language-model-applications/).",
        "All tests were conducted in an authorised environment.",
        "",
        "_Generated by Promptix — ethical adversarial LLM security toolkit._",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")
